version: '3.7'
services:
  service_1:
    image: misbahmehmood/service_1
    build: ./Service_1
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
    environment:
      - PROJECT_URI=${PROJECT_URI}
    deploy:
      replicas: 2

  service_2:
    image: misbahmehmood/service_2
    build: ./Service_2
    ports:
      - target: 5001
        published: 5001
        protocol: tcp
    deploy:
      replicas: 2

  service_3:
    image: misbahmehmood/service_3
    build: ./Service_3
    ports:
      - target: 5002
        published: 5002
        protocol: tcp
    deploy:
      replicas: 2

  service_4:
    image: misbahmehmood/service_4
    build: ./Service_4
    ports:
      - target: 5003
        published: 5003
        protocol: tcp
    environment:
      - PROJECT_URI=${PROJECT_URI}
    deploy:
      replicas: 2