- name: Manager node- install docker and initiate swarm 
  hosts: swarmmanager
  connection: local
  become: true
  roles:
    - installation
    - initiate_swarm
    

- name: Worker node- install docker, add as worker
  hosts: swarmworker
  become: true
  roles:
    - installation
    - add_workers
  

